apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  selector:
    matchLabels:
      app: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
